"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.boolean = exports.alias = void 0;
exports.alias = {
    help: ['h'],
    watch: ['w'],
    version: ['v'],
    project: ['p'],
    build: ['b'],
    target: ['t'],
    module: ['m'],
    declaration: ['d'],
    outFile: ['out'],
};
exports.boolean = [
    'allowJs',
    'allowSyntheticDefaultImports',
    'allowUmdGlobalAccess',
    'allowUnreachableCode',
    'allowUnusedLabels',
    'alwaysStrict',
    'checkJs',
    'declaration',
    'declarationMap',
    'emitDeclarationOnly',
    'disableSizeLimit',
    'disableSourceOfProjectReferenceRedirect',
    'disableSolutionSearching',
    'disableReferencedProjectLoad',
    'downlevelIteration',
    'emitBOM',
    'emitDecoratorMetadata',
    'exactOptionalPropertyTypes',
    'experimentalDecorators',
    'forceConsistentCasingInFileNames',
    'importHelpers',
    'inlineSourceMap',
    'inlineSources',
    'isolatedModules',
    'keyofStringsOnly',
    'noEmit',
    'noEmitHelpers',
    'noEmitOnError',
    'noErrorTruncation',
    'noFallthroughCasesInSwitch',
    'noImplicitAny',
    'noImplicitReturns',
    'noImplicitThis',
    'noStrictGenericChecks',
    'noUnusedLocals',
    'noUnusedParameters',
    'noImplicitUseStrict',
    'noPropertyAccessFromIndexSignature',
    'assumeChangesOnlyAffectDirectDependencies',
    'noLib',
    'noResolve',
    'noUncheckedIndexedAccess',
    'preserveConstEnums',
    'noImplicitOverride',
    'preserveSymlinks',
    'preserveValueImports',
    'composite',
    'incremental',
    'removeComments',
    'skipLibCheck',
    'skipDefaultLibCheck',
    'sourceMap',
    'strict',
    'strictFunctionTypes',
    'strictBindCallApply',
    'strictNullChecks',
    'strictPropertyInitialization',
    'stripInternal',
    'suppressExcessPropertyErrors',
    'suppressImplicitAnyIndexErrors',
    'traceResolution',
    'useUnknownInCatchVariables',
    'resolveJsonModule',
    'esModuleInterop',
    'useDefineForClassFields',
];
