import { DEFAULT_CONTEXT_TOKENS, DEFAULT_FOLLOW_UP_MODE, DEFAULT_STEERING_MODE } from '@zhin.js/ai';
import { DEFAULT_CONTEXT_TAIL_MESSAGE_LIMIT } from '../context/context-tail-limit.js';
import {
  DEFAULT_ALWAYS_LOADED_TOOLS,
  DEFAULT_DEFERRED_TOOLS_CONFIG,
} from '../tool-catalog/types.js';
import type { ZhinAgentConfig } from './zhin-agent-config.js';
import { DEFAULT_WORKER_BASE_TOOLS } from './zhin-agent-constants.js';

export const DEFAULT_CONFIG = {
  persona: 'You are Zhin, an intelligent IM assistant running in Zhin.js. Answer clearly, act through available tools when needed, and never claim actions or results unless confirmed by tool output.',
  maxIterations: 15,
  timeout: 120_000,
  preExecTimeout: 15_000,
  maxSkills: 5,
  maxTools: 12,
  minTopicRounds: 5,
  slidingWindowSize: 5,
  contextTailMessageLimit: DEFAULT_CONTEXT_TAIL_MESSAGE_LIMIT,
  topicChangeThreshold: 0.15,
  rateLimit: {},
  toneAwareness: true,
  chatModel: '',
  visionModel: '',
  contextTokens: DEFAULT_CONTEXT_TOKENS,
  maxHistoryShare: 0.5,
  compaction: {
    enabled: true,
    auto: true,
    keepRecentTokens: 20_000,
    minKeepCount: 2,
  },
  disabledTools: [],
  allowedTools: [],
  execSecurity: 'deny',
  execPreset: 'custom',
  execAllowlist: [],
  execApprovalMode: 'deny',
  subagentExecApprovalMode: 'deny',
  maxParallelSubagents: 5,
  toolExecution: 'tiered',
  subagentAutoContinue: true,
  subagentDirectImDelivery: false,
  workerExecApprovalMode: 'deny',
  taskExecApprovalMode: 'deny',
  maxSubagentIterations: 25,
  subagentTools: [],
  subagentTurnWaitMs: 300_000,
  modelSizeHint: '',
  skillInstructionMaxChars: 0,
  modelHarness: {},
  phaseTrace: false,
  onPhaseTrace: () => {},
  promptTraceVerbose: false,
  promptCacheRetention: 'in_memory',
  promptCacheKeyPrefix: 'zhin',
  deferredToolMaxResults: 8,
  deferredTools: { ...DEFAULT_DEFERRED_TOOLS_CONFIG },
  workerBaseTools: [...DEFAULT_WORKER_BASE_TOOLS],
  platformPromptSectionMaxChars: 2048,
  platformPromptMaxChars: 4096,
  steeringMode: DEFAULT_STEERING_MODE,
  followUpMode: DEFAULT_FOLLOW_UP_MODE,
  policyDenialStopAfter: 2,
  deferredAutoContinue: false,
  deferredAutoContinueMaxDepth: 8,
  outputSchema: false,
} as unknown as Required<ZhinAgentConfig>;
