packages:
  - 'basic/*'
  - 'packages/im/*'
  - 'packages/console/*'
  - 'packages/toolkit/*'
  - 'packages/host/*'
  - 'plugins/adapters/*'
  - 'plugins/features/*'
  - 'plugins/utils/*'
  - 'plugins/services/*'
  - 'examples/*'
  - 'zhin-console'
  - 'docs'
