/**
 * 第二轮审计修复的回归测试
 * - parseCondition：Date 等带原型对象按标量等值处理；未知操作符抛错
 * - migration：无显式 down 时先 dry-run 校验再执行；formatDefault 转义单引号
 */
import { createRequire } from 'node:module';
import { describe, it, expect, beforeEach } from 'vitest';
import { Sqlite } from '../src/dialects/sqlite.js';
import { PG, PostgreSQLDialect } from '../src/dialects/pg.js';
import { DocumentDatabase } from '../src/type/document/database.js';
import { Memory } from '../src/dialects/memory.js';
import { MySQLDialect } from '../src/dialects/mysql.js';
import { MongoDBDialect } from '../src/dialects/mongodb.js';
import { MigrationRunner, defineMigration } from '../src/migration.js';

const require = createRequire(import.meta.url);
let sqliteAvailable = false;
try {
  const { DatabaseSync } = require('node:sqlite');
  const db = new DatabaseSync(':memory:');
  db.close();
  sqliteAvailable = true;
} catch {
  // Node 内置 SQLite 需要 Node.js 22.5+
}

interface TestSchema {
  events: { id: number; created_at: Date; name: string };
}

describe.skipIf(!sqliteAvailable)('audit fixes: parseCondition', () => {
  let db: Sqlite<TestSchema>;

  beforeEach(() => {
    db = new Sqlite<TestSchema>({ filename: ':memory:' });
  });

  it('Date 值应生成等值条件而非静默丢弃', () => {
    const date = new Date('2024-01-01T00:00:00.000Z');
    const { query: sql, params } = db.buildQuery({
      type: 'select',
      tableName: 'events',
      conditions: { created_at: date },
    } as any);
    expect(sql).toContain('WHERE');
    expect(sql).toMatch(/"created_at" = \?/);
    expect(params).toEqual([date]);
  });

  it('普通对象操作符仍正常工作', () => {
    const { query: sql, params } = db.buildQuery({
      type: 'select',
      tableName: 'events',
      conditions: { id: { $gt: 5 } },
    } as any);
    expect(sql).toMatch(/"id" > \?/);
    expect(params).toEqual([5]);
  });

  it('未知操作符应抛错而非静默忽略', () => {
    expect(() =>
      db.buildQuery({
        type: 'select',
        tableName: 'events',
        conditions: { id: { $bogus: 1 } },
      } as any),
    ).toThrow(/unknown operator/);
  });

  it('keeps auto-increment columns in SQLite exact INTEGER PRIMARY KEY form', () => {
    expect(db.dialect.formatColumnDefinition('id', {
      type: 'integer',
      length: 11,
      primary: true,
      autoIncrement: true,
    })).toBe('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
  });
});

describe('audit fixes: PostgreSQL placeholders', () => {
  const db = new PG<TestSchema>({});

  it('maps 64-bit integers and generates identity columns', () => {
    expect(db.dialect.mapColumnType('bigint')).toBe('BIGINT');
    expect(db.dialect.formatColumnDefinition('id', {
      type: 'integer',
      primary: true,
      autoIncrement: true,
    })).toBe('"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('continues numbering after update values', () => {
    const { query, params } = db.buildQuery({
      type: 'update',
      tableName: 'events',
      update: { name: 'renamed' },
      conditions: { id: 1 },
    });
    expect(query).toBe('UPDATE "events" SET "name" = $1 WHERE "id" = $2');
    expect(params).toEqual(['renamed', 1]);
  });

  it('numbers nested conditions without reusing placeholders', () => {
    const { query, params } = db.buildQuery({
      type: 'select',
      tableName: 'events',
      conditions: { $or: [{ id: 1 }, { name: 'second' }] },
    });
    expect(query).toContain(`("id" = $1) OR ("name" = $2)`);
    expect(params).toEqual([1, 'second']);
  });

  it('continues numbering array conditions after update values', () => {
    const { query, params } = db.buildQuery({
      type: 'update',
      tableName: 'events',
      update: { name: 'renamed' },
      conditions: { $or: [{ id: { $in: [1, 2] } }, { id: { $nin: [3, 4] } }] },
    } as any);
    expect(query).toContain('("id" IN ($2, $3)) OR ("id" NOT IN ($4, $5))');
    expect(params).toEqual(['renamed', 1, 2, 3, 4]);
  });

  it('uses the active dialect when migrations format bigint columns', async () => {
    const queries: string[] = [];
    const fake = new PG<any>({}) as any;
    fake.query = async (sql: string) => { queries.push(sql); return []; };
    const context = (new MigrationRunner(fake) as any).createContext();
    await context.createTable('durable_events', {
      time: { type: 'bigint', nullable: false },
    });
    expect(queries[0]).toContain('"time" BIGINT NOT NULL');
  });
});

describe('audit fixes: document and memory contracts', () => {
  it('rejects relational schema alterations for document collections', () => {
    const dialect = { name: 'document' } as any;
    const db = new DocumentDatabase(dialect);
    expect(() => db.buildQuery({
      type: 'alter',
      tableName: 'events',
      alterations: { value: { action: 'add', type: 'text' } },
    } as any)).toThrow(/Document schema alteration is not supported/);
  });

  it('applies declared defaults in the memory dialect', async () => {
    const db = new Memory<any>({}, {
      settings: {
        id: { type: 'integer', primary: true, autoIncrement: true },
        label: { type: 'text', default: "o'clock" },
      },
    });
    await db.start();
    await db.model('settings').insert({} as never);
    await expect(db.model('settings').select()).resolves.toEqual([
      expect.objectContaining({ id: 1, label: "o'clock" }),
    ]);
    await db.stop();
  });
});

describe('audit fixes: driver normalization', () => {
  it('normalizes MySQL boolean and safe bigint fields inside transactions', async () => {
    const dialect = new MySQLDialect<any>({});
    dialect.registerTableSchema('events', {
      enabled: { type: 'boolean' },
      occurred_at: { type: 'bigint' },
    });
    (dialect as any).connection = {
      beginTransaction: async () => undefined,
      commit: async () => undefined,
      rollback: async () => undefined,
      execute: async () => [[{ enabled: 1, occurred_at: '1789978249941' }], [
        { orgTable: 'events', orgName: 'enabled', name: 'enabled' },
        { orgTable: 'events', orgName: 'occurred_at', name: 'occurred_at' },
      ]],
    };
    const transaction = await dialect.beginTransaction();
    await expect(transaction.query('SELECT enabled, occurred_at FROM events')).resolves.toEqual([
      { enabled: true, occurred_at: 1789978249941 },
    ]);
  });

  it('normalizes PostgreSQL bigint fields in pooled transactions', async () => {
    const dialect = new PostgreSQLDialect<any>({ pool: {} });
    const client = {
      query: async (sql: string) => sql === 'BEGIN'
        ? { rows: [], fields: [] }
        : { rows: [{ occurred_at: '1789978249941' }], fields: [{ name: 'occurred_at', dataTypeID: 20 }] },
      release: () => undefined,
    };
    (dialect as any).pool = { connect: async () => client };
    const transaction = await dialect.beginTransaction();
    await expect(transaction.query('SELECT occurred_at FROM events')).resolves.toEqual([
      { occurred_at: 1789978249941 },
    ]);
  });

  it('advances PostgreSQL identity sequences without rounding bigint maxima', async () => {
    const dialect = new PostgreSQLDialect<any>({});
    const calls: Array<{ sql: string; params?: any[] }> = [];
    (dialect as any).query = async (sql: string, params?: any[]) => {
      calls.push({ sql, params });
      if (sql.includes('information_schema.columns')) {
        return [{
          table_name: 'events',
          column_name: 'id',
          data_type: 'bigint',
          is_identity: 'NO',
          column_default: null,
        }];
      }
      if (sql.includes('SELECT MAX')) return [{ max_value: '9007199254740993' }];
      return [];
    };
    await dialect.reconcileDefinitions(new Map([
      ['events', { id: { type: 'bigint', autoIncrement: true } }],
    ]) as any);
    expect(calls.find((call) => call.sql.includes('setval'))?.params?.[2])
      .toBe('9007199254740994');
  });

  it('treats concurrent MongoDB collection creation as idempotent', async () => {
    const dialect = new MongoDBDialect<any>({ url: 'mongodb://localhost', dbName: 'zhin' });
    (dialect as any).db = {
      listCollections: () => ({ hasNext: async () => false }),
      createCollection: async () => { throw Object.assign(new Error('exists'), { code: 48 }); },
    };
    await expect((dialect as any).executeCreateCollection('events')).resolves.toEqual([]);
  });
});

describe.skipIf(!sqliteAvailable)('audit fixes: migration', () => {
  let db: Sqlite<any>;
  let runner: MigrationRunner;

  beforeEach(async () => {
    db = new Sqlite<any>({ filename: ':memory:' });
    await db.start();
    runner = new MigrationRunner(db as any);
  });

  it('无显式 down 且不可反向时，应先校验再执行（数据库不被修改）', async () => {
    await db.query('CREATE TABLE "keep_me" ("id" INTEGER PRIMARY KEY)');

    runner.add(
      defineMigration({
        name: '001_drop_keep_me',
        up: async (ctx) => {
          await ctx.dropTable('keep_me'); // dropTable 无法自动反向
        },
      }),
    );

    await expect(runner.migrate()).rejects.toThrow(/Cannot auto-reverse/);

    // dry-run 校验在执行之前，表不应被删除
    const rows = (await db.query(
      `SELECT name FROM sqlite_master WHERE type='table' AND name='keep_me'`,
    )) as any[];
    expect(rows).toHaveLength(1);
  });

  it('可自动反向的迁移仍正常执行并记录', async () => {
    runner.add(
      defineMigration({
        name: '002_create_table',
        up: async (ctx) => {
          await ctx.createTable('things', {
            id: { type: 'integer', primary: true },
          });
        },
      }),
    );
    const migrated = await runner.migrate();
    expect(migrated).toEqual(['002_create_table']);
    const rows = (await db.query(
      `SELECT name FROM sqlite_master WHERE type='table' AND name='things'`,
    )) as any[];
    expect(rows).toHaveLength(1);
  });

  it('字符串默认值中的单引号应被转义', async () => {
    runner.add(
      defineMigration({
        name: '003_default_escape',
        up: async (ctx) => {
          await ctx.createTable('quotes', {
            id: { type: 'integer', primary: true },
            label: { type: 'text', default: "o'clock" },
          });
        },
      }),
    );
    await runner.migrate();
    await db.query('INSERT INTO "quotes" ("id") VALUES (?)', [1]);
    const rows = (await db.query('SELECT "label" FROM "quotes" WHERE "id" = ?', [1])) as any[];
    expect(rows[0].label).toBe("o'clock");
  });
});
