export const RESERVED_TOOL_NAME_PREFIXES = [
  'internal_',
];

export const RESERVED_TOOL_NAMES = [
  'read_file',
  'write_file',
  'edit_file',
  'list_dir',
  'glob',
  'grep',
  'bash',
  'web_search',
  'web_fetch',
  'todo_read',
  'todo_write',
  'discover',
  'load_tool',
  'load_skill',
  'install_skill',
  'ask_user',
  'tool_search',
  'run_deferred_task',
  'chat_history',
  'user_profile',
  'spawn_task',
  'schedule_list',
  'schedule_add',
  'schedule_preview',
  'schedule_remove',
  'schedule_pause',
  'schedule_resume',
];
