import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    websocket: 'src/websocket.ts',
    'console-api': 'src/console-api.ts',
    'rpc/project-fs': 'src/rpc/project-fs.ts',
  },
  format: ['esm'],
  dts: { compilerOptions: { skipLibCheck: true } },
  clean: true,
  treeshake: true,
  splitting: false,
  sourcemap: false,
  env: {},
  external: [
    '@zhin.js/core',
    '@zhin.js/http',
    '@zhin.js/http-host',
    'zhin.js',
    '@zhin.js/client',
    '@zhin.js/agent',
    '@zhin.js/console-core',
    '@zhin.js/console-types',
    'fs',
    'path',
    'url',
    'child_process',
    'react',
    'react-dom',
    'ws',
    'koa',
    '@koa/router',
    'esbuild',
  ],
  noExternal: [],
  outDir: 'lib',
})
