import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'websocket': 'src/websocket.ts',
  },
  format: ['esm'],
  dts: true,
  clean: true,
  treeshake: true,
  splitting: false,
  sourcemap: false,
  env: {},
  external: [
    '@zhin.js/core',
    '@zhin.js/http',
    '@zhin.js/client',
    '@zhin.js/agent',
    '@zhin.js/console-core',
    '@zhin.js/console-types',
    '@zhin.js/console-app',
    'fs',
    'path',
    'url',
    'child_process',
    'react',
    'react-dom',
    'ws',
    'koa',
    '@koa/router',
    'esbuild',
  ],
  noExternal: [],
  outDir: 'lib',
})
