/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    StyleGuide: typeof import('./src/components/StyleGuide.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
